FROM mcr.microsoft.com/dotnet/sdk:8.0

LABEL author="Malezhskiy Dmitriy"
LABEL email="ffalcrum@gmail.com"

WORKDIR /WebSibguty

COPY Release/ ./

CMD ["dotnet", "Backend.dll", "--urls", "http://0.0.0.0:5188"]

EXPOSE 5188
